export const certificates = [
  {
    title: "Google Certified Educator, Level 2",
    issuer: "Google for Education",
    date: "Issued May 2020 · valid through May 2023",
    category: "Education & AI",
    note: "Advanced knowledge, skills, and competencies to implement and integrate Google for Education tools.",
  },
  {
    title: "Google Certified Educator, Level 1",
    issuer: "Google for Education",
    date: "Issued May 2020 · valid through May 2023",
    category: "Education & AI",
    note: "Foundational competencies for using Google for Education tools in the classroom.",
  },
  {
    title: "Google AI for K12 Educators",
    issuer: "Google",
    date: "Completed July 2025 · score 94",
    category: "Education & AI",
    note: "Using Google AI tools to boost productivity as an education professional.",
  },
  {
    title: "Technical Support Fundamentals",
    issuer: "Google, via Coursera",
    date: "October 2022",
    category: "Education & AI",
    note: "Part of the Google IT Support track.",
  },
  {
    title: "National Certificate II, Computer Hardware Servicing",
    issuer: "TESDA",
    date: "Issued October 2012",
    category: "Hardware & Networking",
    note: "Philippine TVET qualification covering workstation builds, wiring, and network configuration and troubleshooting.",
  },
  {
    title: "Drone Hands-On Flight Training",
    issuer: "CameraHaus Drone Training Center",
    date: "October 2018",
    category: "Hardware & Networking",
    note: "Completed at Amoranto Sports Complex under a CAAP-licensed RPA controller.",
  },
  {
    title: "What The Hack Summit 2016",
    issuer: "GlobalKnowledge PH / CompTIA",
    date: "June 2016, SMX MOA",
    category: "Security",
    note: "Two-day track: ethical hacking, vulnerabilities in critical infrastructure, future threats, cyber law, and collaboration.",
  },
  {
    title: "DataHack 2018: Data Privacy & Cybersecurity Seminar",
    issuer: "GlobalKnowledge PH",
    date: "December 2018, The New Camelot Hotel",
    category: "Security",
    note: "CIPM overview, current cybersecurity trends, and data privacy compliance.",
  },
  {
    title: "Faculty Development Talk: Data Management",
    issuer: "JCSGO Christian Academy",
    date: "December 2018",
    category: "Recognition",
    note: "Certificate of Appreciation for a talk on data management and basic computer handling.",
  },
];
